defaults: &defaults
  adapter:  postgresql
  encoding: unicode
  pool: 5
  host:     localhost

development:
  <<: *defaults
  database: tracker_table
  username: tracker_user
  password: qwertyuiop1

test: &test
  <<: *defaults
  database: tracker_table
  username: tracker_user
  password: qwertyuiop1

production:
    <<: *defaults
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['RDS_DB_NAME'] %>
    username: <%= ENV['RDS_USERNAME'] %>
    password: <%= ENV['RDS_PASSWORD'] %>
    host: <%= ENV['RDS_HOSTNAME'] %>
    port: <%= ENV['RDS_PORT'] %>

cucumber:
  <<: *test
